In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 0.1045605   1.64695886 -0.42400102  1.51427527 -1.13881419]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.1045605   1.64695886 -0.42400102  1.51427527 -1.13881419]


In [6]:
print(np.dot(a, a.T))

6.493110612527611


In [7]:
a = np.random.randn(5, 1)
print(a)

[[-0.95685709]
 [ 0.90273216]
 [-2.54540195]
 [ 0.62222691]
 [-0.02024643]]


In [8]:
print(a.T)

[[-0.95685709  0.90273216 -2.54540195  0.62222691 -0.02024643]]


In [10]:
print(np.dot(a, a.T))

[[ 9.15575483e-01 -8.63785662e-01  2.43558589e+00 -5.95382232e-01
   1.93729359e-02]
 [-8.63785662e-01  8.14925349e-01 -2.29781619e+00  5.61704245e-01
  -1.82770995e-02]
 [ 2.43558589e+00 -2.29781619e+00  6.47907106e+00 -1.58381760e+00
   5.15352913e-02]
 [-5.95382232e-01  5.61704245e-01 -1.58381760e+00  3.87166333e-01
  -1.25978710e-02]
 [ 1.93729359e-02 -1.82770995e-02  5.15352913e-02 -1.25978710e-02
   4.09917753e-04]]
